language: node_js
node_js:
  - lts/*
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
  - pip install --user awscli
  - pip install --user aws-sam-cli
script:
  - npm test
  - sam validate
after_script:
  - codecov
deploy:
  provider: script
  script: sam package --template-file template.yaml --s3-bucket "$AWS_S3_BUCKET_NAME" --output-template-file packaged.yaml && sam deploy --template-file packaged.yaml --parameter-overrides IftttEvent="$IFTTT_EVENT" IftttKey="$IFTTT_KEY" --capabilities CAPABILITY_IAM --stack-name activity-calendar
  skip_cleanup: true
  on:
    branch: master
