language: node_js
node_js:
- '8'
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
- codecov
