service: activity-calendar

provider:
  name: aws
  runtime: nodejs6.10

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline