service: activity-calendar

provider:
  name: aws
  runtime: nodejs6.10

functions:
  app:
    handler: dist/bin/index.handler
    events:
      - http:
          path: ingest
          method: post

plugins:
  - serverless-offline